branches: 
  except:
    - /.*travis.*/

image:
- Visual Studio 2013
- Visual Studio 2015
#- Visual Studio 2017

configuration:
- Debug
- Release

build_script:
  - set arch=
  - set bitness=32
  - if "%arch%"=="Win64" ( set arch= Win64 ; set bitness=32)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%";set vsyear=2017 )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%";set vsyear=2015 )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%";set vsyear=2013 )
  - echo %generator%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\%vsyear%\Community\VC\Auxiliary\Build\vcvars%bitness%.bat"
  - set CXXFLAGS="-D_CRT_SECURE_NO_WARNINGS"
  - cmake "-G%generator%" -H. -B_builds
  - cmake --build _builds
