branches: 
  except:
    - /.*travis.*/

image:
- Visual Studio 2013
- Visual Studio 2015
#- Visual Studio 2017

configuration:
- Debug
- Release

build_script:
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
  - echo %generator%
  - set CXXFLAGS="-D_CRT_SECURE_NO_WARNINGS"
  - cmake "-G %generator%" -H. -B_builds
  - cmake --build _builds
